GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/5ce5b641db04d0327c242981

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amaze Person",
    "subscribedToChannel": "Lucas dev" 
}

###
PATCH  http://localhost:3000/subscribers/5ce5b0f5db04d0327c242980
Content-Type: application/json

{
    "name": "Novo Nome"
}

###
DELETE http://localhost:3000/subscribers/5ce5b0f5db04d0327c242980

